apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
    name: redis
    redis-sentinel: "true"
    role: master
spec:
  containers:
    - name: master
      image: k8s.gcr.io/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
